/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ads.jogorpg;

import ads.jogorpg.DataBase.DbSQL;
import ads.jogorpg.User.User;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author João Marcelo
 */
public class Cadastro extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Txt_Nick = new javax.swing.JTextField();
        Txt_Email = new javax.swing.JTextField();
        Txt_nome = new javax.swing.JTextField();
        Txtx_ConfirmSenha = new javax.swing.JPasswordField();
        Txt_Senha = new javax.swing.JPasswordField();
        Combo_Sex = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        Label_Nick = new javax.swing.JLabel();
        Label_email = new javax.swing.JLabel();
        Label_Senha = new javax.swing.JLabel();
        Label_TxtConfirm = new javax.swing.JLabel();
        Label_None = new javax.swing.JLabel();
        Label_TxtConfirm1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Txt_Nick.setBackground(new java.awt.Color(204, 204, 204));
        Txt_Nick.setForeground(new java.awt.Color(0, 0, 0));
        Txt_Nick.setText("Nome de jogador");
        getContentPane().add(Txt_Nick, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, 160, 30));

        Txt_Email.setBackground(new java.awt.Color(204, 204, 204));
        Txt_Email.setForeground(new java.awt.Color(0, 0, 0));
        Txt_Email.setText("E-mail");
        getContentPane().add(Txt_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 310, 160, 30));

        Txt_nome.setBackground(new java.awt.Color(204, 204, 204));
        Txt_nome.setForeground(new java.awt.Color(0, 0, 0));
        Txt_nome.setText("Nome");
        getContentPane().add(Txt_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 210, 160, 30));

        Txtx_ConfirmSenha.setBackground(new java.awt.Color(204, 204, 204));
        Txtx_ConfirmSenha.setForeground(new java.awt.Color(0, 0, 0));
        Txtx_ConfirmSenha.setText("Senha");
        Txtx_ConfirmSenha.setPreferredSize(new java.awt.Dimension(170, 30));
        getContentPane().add(Txtx_ConfirmSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 410, 160, -1));

        Txt_Senha.setBackground(new java.awt.Color(204, 204, 204));
        Txt_Senha.setForeground(new java.awt.Color(0, 0, 0));
        Txt_Senha.setText("Senha");
        Txt_Senha.setPreferredSize(new java.awt.Dimension(170, 30));
        getContentPane().add(Txt_Senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, 160, 30));

        Combo_Sex.setBackground(new java.awt.Color(204, 204, 204));
        Combo_Sex.setForeground(new java.awt.Color(0, 0, 0));
        Combo_Sex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculo", "Feminino", "N/a" }));
        getContentPane().add(Combo_Sex, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 460, -1, -1));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 490, 110, 30));

        Label_Nick.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Label_Nick.setForeground(new java.awt.Color(255, 255, 255));
        Label_Nick.setText("Nome de Jogador");
        getContentPane().add(Label_Nick, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, 160, -1));

        Label_email.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Label_email.setForeground(new java.awt.Color(255, 255, 255));
        Label_email.setText("E-mail");
        getContentPane().add(Label_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, 160, -1));

        Label_Senha.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Label_Senha.setForeground(new java.awt.Color(255, 255, 255));
        Label_Senha.setText("Senha");
        getContentPane().add(Label_Senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 340, 160, -1));

        Label_TxtConfirm.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Label_TxtConfirm.setForeground(new java.awt.Color(255, 255, 255));
        Label_TxtConfirm.setText("Genero");
        getContentPane().add(Label_TxtConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 440, 160, -1));

        Label_None.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Label_None.setForeground(new java.awt.Color(255, 255, 255));
        Label_None.setText("Seu Nome");
        getContentPane().add(Label_None, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 160, -1));

        Label_TxtConfirm1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Label_TxtConfirm1.setForeground(new java.awt.Color(255, 255, 255));
        Label_TxtConfirm1.setText("Confirmar Senha");
        getContentPane().add(Label_TxtConfirm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 390, 160, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\João Marcelo\\Documents\\JOAO MARCELO\\Facul\\jogoCris\\moldura_maior.png")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\João Marcelo\\Documents\\JOAO MARCELO\\Facul\\jogoCris\\fundo.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DbSQL SQL = new DbSQL();
        boolean Verifica;
        User V = SQL.sqlUserSelectNickName(Txt_Nick.getText());
        System.out.println(V.getNickName());
        
        if(Txt_Nick.getText().equals(V.getNickName())){
            JOptionPane.showMessageDialog(null, "Nome ja existente");
        }else{
            if(Txt_Senha.getText().equals(Txtx_ConfirmSenha.getText())){
                User p1 = new User(0, Txt_nome.getText(), Txt_Nick.getText(), Txt_Email.getText(), Txt_Senha.getText(), (String)Combo_Sex.getSelectedItem());
                SQL.sqlDbUserInsert(p1);
                this.dispose();
                login T1 = new login();
                T1.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(null, "Senhas Divergentes");
            }
            
        }
            
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Combo_Sex;
    private javax.swing.JLabel Label_Nick;
    private javax.swing.JLabel Label_None;
    private javax.swing.JLabel Label_Senha;
    private javax.swing.JLabel Label_TxtConfirm;
    private javax.swing.JLabel Label_TxtConfirm1;
    private javax.swing.JLabel Label_email;
    private javax.swing.JTextField Txt_Email;
    private javax.swing.JTextField Txt_Nick;
    private javax.swing.JPasswordField Txt_Senha;
    private javax.swing.JTextField Txt_nome;
    private javax.swing.JPasswordField Txtx_ConfirmSenha;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
